import { StyleSheet } from 'react-native'
import Color from './Color';
import { Dimensions } from 'react-native';

// Get the window width
const { width: windowWidth } = Dimensions.get('window');

// Purpose: To store all the styles used in the app.
export default Style = StyleSheet.create({
    appContainer: {
      flex: 1,
      height: '100%',
    },
    container: {
      flex: 1,
      backgroundColor: Color.white,
    },
    profileContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 20,
      padding: 10,
      paddingTop: 20,
      paddingLeft: 20,
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      marginBottom: 10,
    },
    profileName: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 5,
    },
    profileInfo: {
      fontSize: 14,
      marginBottom: 5,
      color: Color.gray,
    },
    profileTabBar: {
      backgroundColor: Color.white,
      borderRadius: 10,
    },
    profileTabBarIndicator: {
      backgroundColor: Color.navigatorBg,
      height: 3,
      borderRadius: 3,
    },
    profileTabBarLabel: {
      fontSize: 16,
      fontWeight: 'bold',
      color: Color.navigatorBg,
    },
    settingImagePicker: {
      alignItems: 'center',
      justifyContent: 'center',
  
    },
    label: {
      fontSize: 14,
      marginBottom: 5,
      color: Color.gray,
      marginStart: 5,
    },
    input: {
      height: 40,
      borderColor: Color.lightgrey,
      borderRadius: 5,
      borderWidth: 1,
      marginBottom: 15,
      paddingHorizontal: 10,
    },
    button: {
      backgroundColor: Color.navigatorBg,
      paddingVertical: 10,
      borderRadius: 5,
      width: '100%', 
      alignItems: 'center', 
    },
    buttonPressed: {
      backgroundColor: '#1884c7', 
      transform: [{ scale: 0.98 }], 
    },
    buttonText: {
      color: Color.white,
      fontSize: 16,
      fontWeight: 'bold',
    },
    background: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    overlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)', 
      width: '100%',
      padding: 20,
    },
    appName: {
      fontSize: 36,
      fontWeight: 'bold',
      color: Color.white,
      marginBottom: 30,
    },
    welcomeSlogan: {
      fontSize: 20,
      color: Color.white,
      marginBottom: 30,
      fontWeight: 'bold',
    },
    welcomeDescription: {
      fontSize: 16,
      color: Color.white,
      marginBottom: 200,
      textAlign: 'left',
    },
    welcomeButtonContainer: {
      flexDirection: 'column', 
      alignItems: 'center',
      width: '80%',
      gap: 20, 
    },
    header: {
      fontSize: 30,
      marginBottom: 20,
      textAlign: 'center',
      fontWeight: 'bold',
    },
    slogan: {
      fontSize: 16,
      color: Color.black,
      marginBottom: 100,
      textAlign: 'center',
    },
    strengthIndicator: {
      marginBottom: 10,
    },
    strengthBars: {
      flexDirection: 'row',
      gap: 10,
    },
    strengthBar: {
      flex: 1,
      height: 5,
      borderRadius: 2,
      backgroundColor: '#e0e0e0',
    },
    strengthText: {
      fontSize: 12,
      marginTop: 5,
      color: Color.red,
    },
    confirmText: {
      fontSize: 12,
      marginTop: 5,
      marginBottom: 10,
      color: Color.red,
    },
    underline: {
      color: Color.gray,
      textAlign: 'center',
      textDecorationLine: 'underline',
    },
    forgotPassword: {
      color: '#1DA1F2',
      textAlign: 'center',
      marginVertical: 15,
      fontSize: 16,
      marginTop: 30,
    },
    locationButton: {
      backgroundColor: Color.white,
      justifyContent: 'center',
      padding: 10,
      borderRadius: 5,
      borderColor: Color.lightgray,
      borderWidth: 1,
      marginBottom: 10,
      width: '100%',
      alignSelf: 'flex-start'
    },
    locationButtonContent: {
      flexDirection: 'row',
      paddingHorizontal: 3,
      gap: 10,
    },
    locationText: {
      fontSize: 14,
      flexShrink: 1, 
      numberOfLines: 1, 
      ellipsizeMode: 'tail',
      paddingTop: 3,
    },
    descriptionContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      marginBottom: 10,
      justifyContent: 'space-between',
    },
    descriptionInput: {
      height: 150,
      textAlignVertical: 'top',
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 20,
      alignItems: 'center',
      marginHorizontal: 30,
    },
    createButton: {
      backgroundColor: '#363678',
      paddingVertical: 10,
      paddingHorizontal: 50,
      borderRadius: 5,
      alignItems: 'center', 
      marginTop: 10,
      marginBottom: 50,
    },
    AIbutton: {
      backgroundColor: '#f0f0f0',
      borderRadius: 20,
      padding: 10,
      alignItems: 'center',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.3)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    AImodalContent: {
      backgroundColor: Color.white,
      borderRadius: 10,
      padding: 20,
      width: '80%',
      maxWidth: 400,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
      
    },
    modalInput: {
      borderWidth: 1,
      borderColor: Color.lightgray,
      borderRadius: 5,
      padding: 10,
      minHeight: 100,
      marginBottom: 15,
      textAlignVertical: 'top',
    },
    modalButton: {
      backgroundColor: Color.navigatorBg,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 5,
      alignItems: 'center', 
      marginTop: 10,
      marginBottom: 10,
    },
    activityCard: {
      marginLeft: 20,
      width: "90%",
      height: 300,
      backgroundColor: Color.white,
      borderRadius: 16,
      margin: 10,
    },
    activityCardInner: {
      width: '100%',
      height: '100%',
    },
    activityCardMedia: {
      flex: 1,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      overflow: 'hidden',
    },
    activityCardImage: {
      flex: 1,
      height: '90%',
      width: '100%',
      resizeMode: 'cover',
      marginBottom: 10,
    },
    activityCardTitleText: {
      fontSize: 18,
      fontWeight: 'bold',
      paddingLeft: 15,
      paddingTop: 5,
      paddingBottom: 10,
      color: Color.navigatorBg,
    },
    activityCardContent: {
      flexDirection: 'row',
      height: '10%',
    },
    activityCardText: {
      paddingLeft: 15,
      fontSize: 14,
      fontWeight: 'bold',
    },
    carouselContainer: {
      width: windowWidth,
      justifyContent: 'center',
      alignItems: 'center'
    },
    carouselImage: {
      width: windowWidth,
      height: windowWidth * 0.8,
      borderRadius: 10,
      resizeMode: 'cover'
    },
    carouselIndicatorContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      width: windowWidth - 20,
      marginTop: 10
    },
    carouselIndicator: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginHorizontal: 5
    },
    defaultPressable: {
      borderRadius: 8,
      padding: 6,
    },
    defaultPressed: {
      backgroundColor: Color.lightgray,
      opacity: 0.5,
    },
    exploreCard: {
      width: "100%",
      marginLeft: 9,
      marginBottom: 0,
      borderRadius: 16,
    },
    exploreCardInner: {
      backgroundColor: Color.white,
      borderRadius: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      //overflow: 'hidden',
    },
    exploreCardMedia: {
      height: '70%',
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      overflow: 'hidden',
      paddingBottom: 10,
    },
    exploreCardImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    exploreCardTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      paddingLeft: 10,
      paddingBottom: 10,
      color: Color.navigatorBg,
    },
    exploreCardContent: {
      flexDirection: 'column',
    },
    exploreCardDateView: {
      flexDirection: 'row',
      paddingLeft: 10,
    },
    exploreCardText: {
      paddingLeft: 5,
      fontSize: 14,
      paddingBottom: 5,
      color: Color.gray,
    },
    exploreCardLocationView: {
      flexDirection: 'row',
      paddingLeft: 10,
    },
    masonry: {
      paddingRight: 18,
    },
    filterMenuContainer: {
      width: windowWidth*0.98,
      backgroundColor: Color.white,
      position: 'absolute',
      right: 5,
      marginTop: 45,
      borderRadius: 10,
      top: 10,
      overflow: 'hidden',
      zIndex: 1,
      paddingHorizontal: 20,
    },
    filterIconContainer: {
      backgroundColor: Color.white,
      paddingVertical: 20,
      paddingRight: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterContainer: {
      padding: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    filterButton: {
      width: '25%',
      height: 30,
      backgroundColor: Color.white,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: Color.lightgrey,
      borderWidth: 1,
    },
    filterText: {
      fontSize: 16,
      color: Color.black,
    },
    staticDetailContainer: {
      flex: 1,
      backgroundColor: Color.white,
    },
    ownerInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: Color.lightgrey,
      width: '110%',
      marginLeft: -10,  
      paddingLeft: 10,
    },
    ownerImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginBottom: 10,
      marginLeft: 10,
      resizeMode: 'cover',
    },
    ownerName: {
      marginLeft: 10,
      fontSize: 20,
      color: Color.black,
      marginBottom: 10,
    },
    staticDetailTitleView: {
      marginVertical: 10,
      marginTop: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    staticDetailTitleText: {
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    staticDetailFieldView: {
      marginVertical: 10,
      marginLeft: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    staticDetailFieldText: {
      marginLeft: 10,
      fontSize: 16,
    },
    staticDetailDescriptionView: {
      marginTop: 10,
      marginLeft: 10,
      flexDirection: 'row',
    },
    staticDetailDescriptionText: {
      marginLeft: 10,
      fontSize: 16,
      width: '85%',
      textAlign: 'justify',
    },
    staticDetailMapView: {
      height: 200,
      width: '90%',
      alignSelf: 'center',
    },
    staticDetailCommentsView: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: Color.lightgrey,
      width: '110%',
      marginLeft: -10,
      paddingBottom: 5,
    },
    staticDetailCommentsText: {
      fontSize: 16,
      marginBottom: 5,
      marginLeft: 25,
      marginTop: 10,
      fontWeight: 'bold',
    },
    commentButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
      width: '100%',
      alignContent: 'flex-start',
    },
    commentInput: {
      width: '70%',
      height: 50,
      padding: 10,
      backgroundColor: Color.lightgrey,
      borderRadius: 10,
      marginBottom: 10,
      marginLeft: 10,
    },
    commentButtonText: {
      color: Color.white,
      fontSize: 15,
    },
    timelineCard: {
      width: "90%",
      backgroundColor: Color.white,
      borderRadius: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    searchBar: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 50,
      zIndex: 1,
    },
    calloutContainer: {
      width: 220, 
      height: 200,
      backgroundColor: 'transparent',
      borderRadius: 16,
    },
    calloutCard: {
      flex: 1,
      margin: 0,
      marginLeft: 0,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    locateButton: {
      position: 'absolute',
      bottom: 75,
      right: 10,
    },
    locateIcon:{
      backgroundColor: Color.white,
      borderRadius: 10,
      alignItems: 'center',
      elevation: 5,
      shadowColor: Color.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      padding: 10,
      borderRadius: 25,
    },
    confirmButton: {
      width: '30%',
      position: 'absolute',
      bottom: 20,
      alignSelf: 'center',
      elevation: 5,
      shadowColor: Color.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    confirmButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '600',
    },
    userComment: {
      borderLeftWidth: 3,
      borderLeftColor: Color.lightgrey,
    },
    commentOwnerPicture: {
      width: 30,
      height: 30,
      borderRadius: 15,
      marginLeft: 10,
    },
    commentUsername: {
      marginLeft: 10,
      marginTop: 5,
      fontSize: 16,
      fontWeight: 'bold',
      color: Color.navigatorBg,
    },
    commentText: {
      marginLeft: 10,
      fontSize: 16,
      marginTop: 2,   
    },
    leaveView: {
      position: 'absolute',
      bottom: 0,
      width: '100%',
      height: 60,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Color.white,
      borderTopColor: Color.lightgrey,
      borderTopWidth: 1,
      paddingBottom: 10,
    },
    joinButtonText: {
      color: Color.white,
      fontSize: 18,
    },
    notifModalContainer: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    pickerContainer: {
      backgroundColor: Color.white,
      width: '100%',
      paddingBottom: 20, 
    },
    doneButton: {
      alignSelf: 'flex-end',
      padding: 12,
      backgroundColor: Color.white,
    },
    modalButtonText: {
      color: 'black',
      fontSize: 16,
      fontWeight: '500',
    },
    commentEditModalContainer: {
      backgroundColor: 'white',
      height: '10%',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    commentEditModalContent: {
      width: '80%',
      padding: 20,
      backgroundColor: 'white',
      borderRadius: 10,
      alignItems: 'center',
    },
    AI: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    noResultsText: {
      fontSize: 18,
      color: Color.black,
    },
    noJoinedText: {
      fontSize: 20,
      color: 'black',
      marginTop: 10,
    },
    arrowLottie: {
      width: 70,
      height: 70,
      position: 'absolute',
      top: -10,
      left: 60,
    },
    noJoinedLottie: {
      width: 300,
      height: 300,
      alignSelf: 'center',
    },
  });